- name: run the playbook tasks on the localhost
  hosts: localhost
  tasks:

#  - name: Read vars from secrets file
#    include_vars: "{{ secrets_file }}"
#    tags:
#      - always

#  - name: Do something
#    debug:
#      msg: "System {{ top_secret_password }}"

  - haproxy:
      state: enabled
      host: web01
      fail_on_not_found: yes
      socket: /usr/local/var/run/haproxy.sock
      weight: "{{ weight }}"
      backend: nodes
