---
#- name: dump hostvars output
#  debug:
#    msg: '{{ hostvars }}'
#  when: inventory_hostname == "t07.ams.surfconext.nl"

#- name: dump test output
#  debug:
#    msg: '{{ java_blauwrood_servers }}'
#  when: inventory_hostname == "t07.ams.surfconext.nl"

- name: do something
  lb_infra_ha_proxy:
    java_blauwrood_servers: "{{ java_blauwrood_servers }}"
    php_blauwrood_servers: "{{ php_blauwrood_servers }}"
    weight: "{{ weight }}"
    color: "{{ color }}"
    app_name: "{{ app_name }}"
    app_type: "{{ app_type }}"
  register: results

- name: dump test output
  debug:
    msg: '{{ results }}'
  when: inventory_hostname == "t07.ams.surfconext.nl"

#- name: set weights
#  haproxy:
#    state: enabled
#    host: "{{ item.host }}"
#    fail_on_not_found: no
#    socket: "{{ item.socket }}"
#    weight: "{{ item.weight }}"
#    backend: "{{ item.backend }}"
#  with_items: "{{ results.haproxy_items }}"


